spring.application.name=huskyplan
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/huskyplan}
spring.datasource.username=${DB_USER:huskyplan}
spring.datasource.password=${DB_PASSWORD:huskyplan}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
server.error.include-message=always
